global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "kafka-connect"
    static_configs:
      - targets: ['kafka-connect:9998']
        labels:
          env: "dev"
          kafka_connect_cluster_id: "cluster1"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
  
  # - job_name: "node-exporter"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]