global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'connect'
    static_configs:
      - targets: ['kafka-connect:9998']
        labels:
          env: "dev"
          cluster: "cluster1"
  
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]